#include "codegen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int codegen_generate(const ASTNode *program, const char *output_filepath) {
    if (!program || program->type != AST_PROGRAM) {
        fprintf(stderr, "[CodeGen Error] Root node must be AST_PROGRAM\n");
        return -1;
    }

    FILE *out = fopen(output_filepath, "w");
    if (!out) {
        fprintf(stderr, "[CodeGen Error] Failed to open output file %s\n", output_filepath);
        return -1;
    }

    const char *net_name = program->value ? program->value : "Network";
    
    // 1. Scan children of Program to gather structural info
    int pool_in = 28;
    (void)pool_in;
    int pool_out = 4;
    int has_pool = 0;
    
    int num_layers = 0;
    int layer_dim = 16;
    double layer_kerr[10] = {0};
    double layer_gain[10] = {1.0};
    
    int readout_classes = 10;
    
    double lr = 0.05;
    int epochs = 1000;
    int batch_size = 10;
    int early_stop = 0;
    double phase_noise = 0.0;
    double shot_noise = 0.0;
    
    ASTNode *child = program->children;
    while (child) {
        if (child->type == AST_LAYER_DECL) {
            if (strcmp(child->value, "pool") == 0) {
                has_pool = 1;
                ASTNode *p1 = child->children;
                if (p1 && p1->type == AST_NUMBER_LITERAL) {
                    pool_in = (int)p1->num_value;
                    ASTNode *p2 = p1->next;
                    if (p2 && p2->type == AST_NUMBER_LITERAL) {
                        pool_out = (int)p2->num_value;
                    }
                }
            } else if (strcmp(child->value, "unitary") == 0) {
                int idx = num_layers++;
                ASTNode *p1 = child->children;
                if (p1 && p1->type == AST_NUMBER_LITERAL) {
                    layer_dim = (int)p1->num_value;
                    // Read config attributes
                    ASTNode *cfg = p1->next;
                    layer_kerr[idx] = 0.0;
                    layer_gain[idx] = 1.0;
                    while (cfg && cfg->type == AST_CONFIG_PAIR) {
                        if (strcmp(cfg->value, "kerr") == 0) {
                            layer_kerr[idx] = cfg->num_value;
                        } else if (strcmp(cfg->value, "gain") == 0) {
                            layer_gain[idx] = cfg->num_value;
                        }
                        cfg = cfg->next;
                    }
                }
            } else if (strcmp(child->value, "softmax") == 0) {
                ASTNode *p1 = child->children;
                if (p1 && p1->type == AST_NUMBER_LITERAL) {
                    readout_classes = (int)p1->num_value;
                }
            }
        } else if (child->type == AST_TRAIN_BLOCK) {
            ASTNode *cfg = child->children;
            while (cfg && cfg->type == AST_CONFIG_PAIR) {
                if (strcmp(cfg->value, "lr") == 0) {
                    lr = cfg->num_value;
                } else if (strcmp(cfg->value, "epochs") == 0) {
                    epochs = (int)cfg->num_value;
                } else if (strcmp(cfg->value, "batch_size") == 0) {
                    batch_size = (int)cfg->num_value;
                } else if (strcmp(cfg->value, "early_stop") == 0) {
                    early_stop = (int)cfg->num_value;
                } else if (strcmp(cfg->value, "phase_noise") == 0) {
                    phase_noise = cfg->num_value;
                } else if (strcmp(cfg->value, "shot_noise") == 0) {
                    shot_noise = cfg->num_value;
                }
                cfg = cfg->next;
            }
        }
        child = child->next;
    }

    // Print header
    fprintf(out, "// Generated by PhoLang Compiler for network: %s\n", net_name);
    fprintf(out, "#include \"../core/photonic.h\"\n");
    fprintf(out, "#include \"../sim/photonic_sim.h\"\n");
    fprintf(out, "#include \"../training/gradient_analytic.h\"\n");
    fprintf(out, "#include \"../core/loss.h\"\n");
    fprintf(out, "#include \"../core/memory.h\"\n");
    fprintf(out, "#include \"../examples/mnist_small/pooling.h\"\n");
    fprintf(out, "#include <stdio.h>\n");
    fprintf(out, "#include <stdlib.h>\n");
    fprintf(out, "#include <math.h>\n");
    fprintf(out, "#include <string.h>\n");
    fprintf(out, "#ifdef _OPENMP\n");
    fprintf(out, "#include <omp.h>\n");
    fprintf(out, "#endif\n\n");
    
    fprintf(out, "// Structural Parameters\n");
    fprintf(out, "#define NUM_LAYERS %d\n", num_layers);
    fprintf(out, "#define LAYER_DIM %d\n", layer_dim);
    fprintf(out, "#define READOUT_CLASSES %d\n", readout_classes);
    fprintf(out, "#define BATCH_SIZE %d\n", batch_size);
    fprintf(out, "#define MAX_EPOCHS %d\n", epochs);
    fprintf(out, "#define LEARNING_RATE %f\n", lr);
    fprintf(out, "#define EARLY_STOP %d\n", early_stop);
    fprintf(out, "#define PHASE_NOISE %f\n", phase_noise);
    fprintf(out, "#define SHOT_NOISE %f\n\n", shot_noise);
    
    // Dataset Parser
    fprintf(out, "// Simple CSV data parser\n");
    fprintf(out, "int load_mnist_data(const char *filename, double *images, double *labels, int max_rows) {\n");
    fprintf(out, "    FILE *f = fopen(filename, \"r\");\n");
    fprintf(out, "    if (!f) {\n");
    fprintf(out, "        fprintf(stderr, \"[Error] Failed to open dataset: %%s\\n\", filename);\n");
    fprintf(out, "        return 0;\n");
    fprintf(out, "    }\n");
    fprintf(out, "    char line[65536];\n");
    fprintf(out, "    int row_count = 0;\n");
    fprintf(out, "    // Skip header\n");
    fprintf(out, "    if (!fgets(line, sizeof(line), f)) {\n");
    fprintf(out, "        fclose(f);\n");
    fprintf(out, "        return 0;\n");
    fprintf(out, "    }\n");
    fprintf(out, "    while (fgets(line, sizeof(line), f) && row_count < max_rows) {\n");
    fprintf(out, "        char *token = strtok(line, \",\");\n");
    fprintf(out, "        if (!token) continue;\n");
    fprintf(out, "        labels[row_count] = atof(token);\n");
    fprintf(out, "        for (int i = 0; i < 784; i++) {\n");
    fprintf(out, "            token = strtok(NULL, \",\");\n");
    fprintf(out, "            if (token) {\n");
    fprintf(out, "                images[row_count * 784 + i] = atof(token) / 255.0;\n");
    fprintf(out, "            } else {\n");
    fprintf(out, "                images[row_count * 784 + i] = 0.0;\n");
    fprintf(out, "            }\n");
    fprintf(out, "        }\n");
    fprintf(out, "        row_count++;\n");
    fprintf(out, "    }\n");
    fprintf(out, "    fclose(f);\n");
    fprintf(out, "    return row_count;\n");
    fprintf(out, "}\n\n");
    
    // Initialize network
    fprintf(out, "SimState init_network() {\n");
    fprintf(out, "    SimState sim = sim_init(NUM_LAYERS, LAYER_DIM);\n");
    for (int i = 0; i < num_layers; i++) {
        fprintf(out, "    sim.layers[%d].kerr_gamma = %f;\n", i, layer_kerr[i]);
        fprintf(out, "    sim.layers[%d].detector_gain = %f;\n", i, layer_gain[i]);
    }
    fprintf(out, "    // Initialize with unitary matrices perturbed by slight noise to break symmetry\n");
    fprintf(out, "    for (int l = 0; l < NUM_LAYERS; l++) {\n");
    fprintf(out, "        for (int i = 0; i < LAYER_DIM; i++) {\n");
    fprintf(out, "            for (int j = 0; j < LAYER_DIM; j++) {\n");
    fprintf(out, "                double noise_r = ((double)rand() / RAND_MAX - 0.5) * 0.1;\n");
    fprintf(out, "                double noise_i = ((double)rand() / RAND_MAX - 0.5) * 0.1;\n");
    fprintf(out, "                if (i == j) {\n");
    fprintf(out, "                    sim.layers[l].weights.data[i * LAYER_DIM + j] = complex_new(1.0 + noise_r, noise_i);\n");
    fprintf(out, "                } else {\n");
    fprintf(out, "                    sim.layers[l].weights.data[i * LAYER_DIM + j] = complex_new(noise_r, noise_i);\n");
    fprintf(out, "                }\n");
    fprintf(out, "            }\n");
    fprintf(out, "        }\n");
    fprintf(out, "    }\n");
    fprintf(out, "    return sim;\n");
    fprintf(out, "}\n\n");

    // Forward pass helper
    fprintf(out, "// Single sample forward pass with pooling\n");
    fprintf(out, "void forward_pass(SimState *sim, const double *image_784, Complex *out_final, Complex *out_intermediate) {\n");
    if (has_pool) {
        fprintf(out, "    double pool_buf[%d];\n", pool_out * pool_out);
        fprintf(out, "    optical_lens_pool_28_to_%d(image_784, pool_buf);\n", pool_out);
        fprintf(out, "    Complex input_complex[LAYER_DIM];\n");
        fprintf(out, "    for (int i = 0; i < LAYER_DIM; i++) {\n");
        fprintf(out, "        if (i < %d) {\n", pool_out * pool_out);
        fprintf(out, "            input_complex[i] = complex_new(pool_buf[i], 0.0);\n");
        fprintf(out, "        } else {\n");
        fprintf(out, "            input_complex[i] = complex_new(0.0, 0.0);\n");
        fprintf(out, "        }\n");
        fprintf(out, "    }\n");
    } else {
        fprintf(out, "    Complex input_complex[LAYER_DIM];\n");
        fprintf(out, "    for (int i = 0; i < LAYER_DIM; i++) {\n");
        fprintf(out, "        if (i < 784) {\n");
        fprintf(out, "            input_complex[i] = complex_new(image_784[i], 0.0);\n");
        fprintf(out, "        } else {\n");
        fprintf(out, "            input_complex[i] = complex_new(0.0, 0.0);\n");
        fprintf(out, "        }\n");
        fprintf(out, "    }\n");
    }
    
    fprintf(out, "    // Forward through layer 0 -> intermediate\n");
    fprintf(out, "    photonic_layer_forward(&sim->layers[0], input_complex, out_intermediate);\n");
    fprintf(out, "    // Forward through layer 1 -> out_final\n");
    fprintf(out, "    photonic_layer_forward(&sim->layers[1], out_intermediate, out_final);\n");
    fprintf(out, "}\n\n");

    // Main training loop
    fprintf(out, "int main(int argc, char **argv) {\n");
    fprintf(out, "    printf(\"=== Generated %s Network Execution ===\\n\");\n", net_name);
    fprintf(out, "    #ifdef _OPENMP\n");
    fprintf(out, "    printf(\"OpenMP is enabled. Max threads: %%d\\\\n\", omp_get_max_threads());\n");
    fprintf(out, "    #else\n");
    fprintf(out, "    printf(\"OpenMP is disabled.\\\\n\");\n");
    fprintf(out, "    #endif\n");
    fprintf(out, "    const char *data_path = \"data/mnist_small.csv\";\n");
    fprintf(out, "    double train_phase = PHASE_NOISE;\n");
    fprintf(out, "    double train_shot = SHOT_NOISE;\n");
    fprintf(out, "    double test_phase = PHASE_NOISE;\n");
    fprintf(out, "    double test_shot = SHOT_NOISE;\n");
    fprintf(out, "    int seed = 42;\n");
    fprintf(out, "    int max_rows = 1000;\n\n");
    fprintf(out, "    for (int i = 1; i < argc; i++) {\n");
    fprintf(out, "        if (strcmp(argv[i], \"--phase-noise\") == 0 && i + 1 < argc) {\n");
    fprintf(out, "            double v = atof(argv[++i]);\n");
    fprintf(out, "            train_phase = v;\n");
    fprintf(out, "            test_phase = v;\n");
    fprintf(out, "        } else if (strcmp(argv[i], \"--shot-noise\") == 0 && i + 1 < argc) {\n");
    fprintf(out, "            double v = atof(argv[++i]);\n");
    fprintf(out, "            train_shot = v;\n");
    fprintf(out, "            test_shot = v;\n");
    fprintf(out, "        } else if (strcmp(argv[i], \"--train-phase-noise\") == 0 && i + 1 < argc) {\n");
    fprintf(out, "            train_phase = atof(argv[++i]);\n");
    fprintf(out, "        } else if (strcmp(argv[i], \"--train-shot-noise\") == 0 && i + 1 < argc) {\n");
    fprintf(out, "            train_shot = atof(argv[++i]);\n");
    fprintf(out, "        } else if (strcmp(argv[i], \"--test-phase-noise\") == 0 && i + 1 < argc) {\n");
    fprintf(out, "            test_phase = atof(argv[++i]);\n");
    fprintf(out, "        } else if (strcmp(argv[i], \"--test-shot-noise\") == 0 && i + 1 < argc) {\n");
    fprintf(out, "            test_shot = atof(argv[++i]);\n");
    fprintf(out, "        } else if (strcmp(argv[i], \"--seed\") == 0 && i + 1 < argc) {\n");
    fprintf(out, "            seed = atoi(argv[++i]);\n");
    fprintf(out, "        } else if (strcmp(argv[i], \"--max-rows\") == 0 && i + 1 < argc) {\n");
    fprintf(out, "            max_rows = atoi(argv[++i]);\n");
    fprintf(out, "        } else if (argv[i][0] != '-') {\n");
    fprintf(out, "            data_path = argv[i];\n");
    fprintf(out, "        }\n");
    fprintf(out, "    }\n");
    fprintf(out, "    srand(seed);\n");
    fprintf(out, "    printf(\"Parameters: seed=%%d, train_phase=%%.4f rad, train_shot=%%.4f, test_phase=%%.4f rad, test_shot=%%.4f\\\\n\", seed, train_phase, train_shot, test_phase, test_shot);\n\n");
    
    fprintf(out, "    // 1. Load Dataset\n");
    fprintf(out, "    double *dataset_x = malloc(max_rows * 784 * sizeof(double));\n");
    fprintf(out, "    double *dataset_y = malloc(max_rows * sizeof(double));\n");
    fprintf(out, "    int num_samples = load_mnist_data(data_path, dataset_x, dataset_y, max_rows);\n");
    fprintf(out, "    if (num_samples <= 0) {\n");
    fprintf(out, "        fprintf(stderr, \"[Error] Could not load dataset from %%s\\n\", data_path);\n");
    fprintf(out, "        free(dataset_x); free(dataset_y);\n");
    fprintf(out, "        return 1;\n");
    fprintf(out, "    }\n");
    fprintf(out, "    int num_train = (int)(num_samples * 0.8);\n");
    fprintf(out, "    int num_test = num_samples - num_train;\n");
    fprintf(out, "    printf(\"Loaded %%d samples. Split: %%d Train, %%d Test\\n\", num_samples, num_train, num_test);\n\n");
    
    fprintf(out, "    // 2. Init Network\n");
    fprintf(out, "    SimState sim = init_network();\n");
    fprintf(out, "    sim.shot_noise = train_shot;\n");
    fprintf(out, "    for (int l = 0; l < NUM_LAYERS; l++) {\n");
    fprintf(out, "        sim.layers[l].phase_noise = train_phase;\n");
    fprintf(out, "    }\n\n");
    fprintf(out, "    Matrix best_weights[NUM_LAYERS];\n");
    fprintf(out, "    for (int l = 0; l < NUM_LAYERS; l++) {\n");
    fprintf(out, "        best_weights[l] = matrix_new(LAYER_DIM, LAYER_DIM);\n");
    fprintf(out, "    }\n");
    fprintf(out, "    double best_test_loss = 1e9;\n");
    fprintf(out, "    int patience_counter = 0;\n");
    fprintf(out, "    int best_epoch = 0;\n\n");
    
    fprintf(out, "    // 3. SGD Training Loop\n");
    fprintf(out, "    for (int epoch = 1; epoch <= MAX_EPOCHS; epoch++) {\n");
    fprintf(out, "        sim.shot_noise = train_shot;\n");
    fprintf(out, "        for (int l = 0; l < NUM_LAYERS; l++) {\n");
    fprintf(out, "            sim.layers[l].phase_noise = train_phase;\n");
    fprintf(out, "        }\n");
    fprintf(out, "        double total_loss = 0.0;\n");
    fprintf(out, "        int correct_predictions = 0;\n\n");
    
    fprintf(out, "        for (int i = 0; i < num_train; i += BATCH_SIZE) {\n");
    fprintf(out, "            // Accumulators\n");
    fprintf(out, "            Matrix grad_l0_accum = matrix_new(LAYER_DIM, LAYER_DIM);\n");
    fprintf(out, "            Matrix grad_l1_accum = matrix_new(LAYER_DIM, LAYER_DIM);\n");
    
    fprintf(out, "            int current_batch_size = (i + BATCH_SIZE > num_train) ? (num_train - i) : BATCH_SIZE;\n\n");
    
    fprintf(out, "            #pragma omp parallel for reduction(+:total_loss, correct_predictions)\n");
    fprintf(out, "            for (int b = 0; b < current_batch_size; b++) {\n");
    fprintf(out, "                int sample_idx = i + b;\n");
    fprintf(out, "                const double *img = &dataset_x[sample_idx * 784];\n");
    fprintf(out, "                int label = (int)dataset_y[sample_idx];\n\n");
    
    fprintf(out, "                double target[READOUT_CLASSES] = {0};\n");
    fprintf(out, "                target[label] = 1.0;\n\n");
    
    fprintf(out, "                Complex out_final[LAYER_DIM];\n");
    fprintf(out, "                Complex out_inter[LAYER_DIM];\n");
    fprintf(out, "                forward_pass(&sim, img, out_final, out_inter);\n\n");
    
    fprintf(out, "                double probs[READOUT_CLASSES] = {0};\n");
    fprintf(out, "                double loss = loss_cross_entropy_softmax_optical(out_final, sim.layers[1].detector_gain, target, READOUT_CLASSES, probs);\n");
    fprintf(out, "                total_loss += loss;\n\n");
    
    fprintf(out, "                int max_class = 0;\n");
    fprintf(out, "                double max_prob = -1.0;\n");
    fprintf(out, "                for (int c = 0; c < READOUT_CLASSES; c++) {\n");
    fprintf(out, "                    if (probs[c] > max_prob) {\n");
    fprintf(out, "                        max_prob = probs[c];\n");
    fprintf(out, "                        max_class = c;\n");
    fprintf(out, "                    }\n");
    fprintf(out, "                }\n");
    fprintf(out, "                if (max_class == label) {\n");
    fprintf(out, "                    correct_predictions++;\n");
    fprintf(out, "                }\n\n");
    
    fprintf(out, "                // Backpropagation\n");
    fprintf(out, "                Complex loss_grad[LAYER_DIM] = {0};\n");
    fprintf(out, "                loss_cross_entropy_softmax_optical_grad(out_final, sim.layers[1].detector_gain, target, READOUT_CLASSES, loss_grad);\n\n");
    
    fprintf(out, "                // Layer 1 Backward\n");
    fprintf(out, "                Complex g_l1_buf[LAYER_DIM * LAYER_DIM];\n");
    fprintf(out, "                Matrix g_l1 = { .rows = LAYER_DIM, .cols = LAYER_DIM, .data = g_l1_buf };\n");
    fprintf(out, "                Complex in_g_l1[LAYER_DIM];\n");
    fprintf(out, "                photonic_layer_backward(&sim.layers[1].weights, out_inter, loss_grad, sim.layers[1].kerr_gamma, &g_l1, in_g_l1, LAYER_DIM);\n\n");
    
    fprintf(out, "                // Layer 0 Backward\n");
    fprintf(out, "                Complex g_l0_buf[LAYER_DIM * LAYER_DIM];\n");
    fprintf(out, "                Matrix g_l0 = { .rows = LAYER_DIM, .cols = LAYER_DIM, .data = g_l0_buf };\n");
    fprintf(out, "                Complex in_g_l0[LAYER_DIM];\n");
    if (has_pool) {
        fprintf(out, "                double pool_temp[%d];\n", pool_out * pool_out);
        fprintf(out, "                optical_lens_pool_28_to_%d(img, pool_temp);\n", pool_out);
        fprintf(out, "                Complex in_c[LAYER_DIM];\n");
        fprintf(out, "                for (int k = 0; k < LAYER_DIM; k++) {\n");
        fprintf(out, "                    if (k < %d) {\n", pool_out * pool_out);
        fprintf(out, "                        in_c[k] = complex_new(pool_temp[k], 0.0);\n");
        fprintf(out, "                    } else {\n");
        fprintf(out, "                        in_c[k] = complex_new(0.0, 0.0);\n");
        fprintf(out, "                    }\n");
        fprintf(out, "                }\n");
        fprintf(out, "                photonic_layer_backward(&sim.layers[0].weights, in_c, in_g_l1, sim.layers[0].kerr_gamma, &g_l0, in_g_l0, LAYER_DIM);\n\n");
    } else {
        fprintf(out, "                Complex in_c[LAYER_DIM];\n");
        fprintf(out, "                for (int k = 0; k < LAYER_DIM; k++) {\n");
        fprintf(out, "                    if (k < 784) {\n");
        fprintf(out, "                        in_c[k] = complex_new(img[k], 0.0);\n");
        fprintf(out, "                    } else {\n");
        fprintf(out, "                        in_c[k] = complex_new(0.0, 0.0);\n");
        fprintf(out, "                    }\n");
        fprintf(out, "                }\n");
        fprintf(out, "                photonic_layer_backward(&sim.layers[0].weights, in_c, in_g_l1, sim.layers[0].kerr_gamma, &g_l0, in_g_l0, LAYER_DIM);\n\n");
    }
    
    fprintf(out, "                // Add to accumulated batch gradients\n");
    fprintf(out, "                #pragma omp critical\n");
    fprintf(out, "                {\n");
    fprintf(out, "                    for (int idx = 0; idx < LAYER_DIM * LAYER_DIM; idx++) {\n");
    fprintf(out, "                        grad_l0_accum.data[idx] = complex_add(grad_l0_accum.data[idx], g_l0.data[idx]);\n");
    fprintf(out, "                        grad_l1_accum.data[idx] = complex_add(grad_l1_accum.data[idx], g_l1.data[idx]);\n");
    fprintf(out, "                    }\n");
    fprintf(out, "                }\n");
    fprintf(out, "            }\n\n");
    
    fprintf(out, "            // Average accumulated batch gradients\n");
    fprintf(out, "            for (int idx = 0; idx < LAYER_DIM * LAYER_DIM; idx++) {\n");
    fprintf(out, "                grad_l0_accum.data[idx] = complex_new(grad_l0_accum.data[idx].real / current_batch_size, grad_l0_accum.data[idx].imag / current_batch_size);\n");
    fprintf(out, "                grad_l1_accum.data[idx] = complex_new(grad_l1_accum.data[idx].real / current_batch_size, grad_l1_accum.data[idx].imag / current_batch_size);\n");
    fprintf(out, "            }\n\n");
    
    fprintf(out, "            Matrix G_skew_l0 = matrix_new(LAYER_DIM, LAYER_DIM);\n");
    fprintf(out, "            Matrix G_skew_l1 = matrix_new(LAYER_DIM, LAYER_DIM);\n");
    fprintf(out, "            compute_skew_hermitian(&grad_l0_accum, &sim.layers[0].weights, &G_skew_l0);\n");
    fprintf(out, "            compute_skew_hermitian(&grad_l1_accum, &sim.layers[1].weights, &G_skew_l1);\n\n");
    
    fprintf(out, "            cayley_update(&sim.layers[0].weights, &G_skew_l0, LEARNING_RATE);\n");
    fprintf(out, "            cayley_update(&sim.layers[1].weights, &G_skew_l1, LEARNING_RATE);\n\n");
    
    fprintf(out, "            matrix_free(&grad_l0_accum); matrix_free(&grad_l1_accum);\n");
    fprintf(out, "            matrix_free(&G_skew_l0); matrix_free(&G_skew_l1);\n");
    fprintf(out, "        }\n\n");
    
    fprintf(out, "        // 4. Test Set Evaluation Pass\n");
    fprintf(out, "        sim.shot_noise = test_shot;\n");
    fprintf(out, "        for (int l = 0; l < NUM_LAYERS; l++) {\n");
    fprintf(out, "            sim.layers[l].phase_noise = test_phase;\n");
    fprintf(out, "        }\n");
    fprintf(out, "        double test_loss = 0.0;\n");
    fprintf(out, "        int test_correct = 0;\n");
    fprintf(out, "        #pragma omp parallel for reduction(+:test_loss, test_correct)\n");
    fprintf(out, "        for (int i = 0; i < num_test; i++) {\n");
    fprintf(out, "            int sample_idx = num_train + i;\n");
    fprintf(out, "            const double *img = &dataset_x[sample_idx * 784];\n");
    fprintf(out, "            int label = (int)dataset_y[sample_idx];\n");
    fprintf(out, "            double target[READOUT_CLASSES] = {0};\n");
    fprintf(out, "            target[label] = 1.0;\n");
    fprintf(out, "            Complex out_final[LAYER_DIM];\n");
    fprintf(out, "            Complex out_inter[LAYER_DIM];\n");
    fprintf(out, "            forward_pass(&sim, img, out_final, out_inter);\n");
    fprintf(out, "            double probs[READOUT_CLASSES] = {0};\n");
    fprintf(out, "            double loss = loss_cross_entropy_softmax_optical(out_final, sim.layers[1].detector_gain, target, READOUT_CLASSES, probs);\n");
    fprintf(out, "            test_loss += loss;\n");
    fprintf(out, "            int max_class = 0;\n");
    fprintf(out, "            double max_prob = -1.0;\n");
    fprintf(out, "            for (int c = 0; c < READOUT_CLASSES; c++) {\n");
    fprintf(out, "                if (probs[c] > max_prob) {\n");
    fprintf(out, "                    max_prob = probs[c];\n");
    fprintf(out, "                    max_class = c;\n");
    fprintf(out, "                }\n");
    fprintf(out, "            }\n");
    fprintf(out, "            if (max_class == label) {\n");
    fprintf(out, "                test_correct++;\n");
    fprintf(out, "            }\n");
    fprintf(out, "        }\n\n");
    
    fprintf(out, "        double avg_train_loss = total_loss / num_train;\n");
    fprintf(out, "        double train_acc = 100.0 * correct_predictions / num_train;\n");
    fprintf(out, "        double avg_test_loss = test_loss / num_test;\n");
    fprintf(out, "        double test_acc = 100.0 * test_correct / num_test;\n\n");
    fprintf(out, "        if (epoch %% 1 == 0 || epoch == MAX_EPOCHS) {\n");
    fprintf(out, "            printf(\"Epoch %%3d | Train Loss: %%.6f | Train Acc: %%.2f%%%% | Test Loss: %%.6f | Test Acc: %%.2f%%%%\\n\", epoch, avg_train_loss, train_acc, avg_test_loss, test_acc);\n");
    fprintf(out, "        }\n\n");
    fprintf(out, "        if (avg_test_loss < best_test_loss) {\n");
    fprintf(out, "            best_test_loss = avg_test_loss;\n");
    fprintf(out, "            patience_counter = 0;\n");
    fprintf(out, "            best_epoch = epoch;\n");
    fprintf(out, "            for (int l = 0; l < NUM_LAYERS; l++) {\n");
    fprintf(out, "                for (int idx = 0; idx < LAYER_DIM * LAYER_DIM; idx++) {\n");
    fprintf(out, "                    best_weights[l].data[idx] = sim.layers[l].weights.data[idx];\n");
    fprintf(out, "                }\n");
    fprintf(out, "            }\n");
    fprintf(out, "        } else {\n");
    fprintf(out, "            patience_counter++;\n");
    fprintf(out, "        }\n\n");
    fprintf(out, "        if (EARLY_STOP > 0 && patience_counter >= EARLY_STOP) {\n");
    fprintf(out, "            printf(\"Early stopping triggered! No improvement for %%d epochs. Best Epoch: %%d (Test Loss: %%.6f).\\n\", EARLY_STOP, best_epoch, best_test_loss);\n");
    fprintf(out, "            break;\n");
    fprintf(out, "        }\n");
    fprintf(out, "    }\n\n");
    
    fprintf(out, "    printf(\"Restoring best weights from epoch %%d (Test Loss: %%.6f) for evaluation...\\n\", best_epoch, best_test_loss);\n");
    fprintf(out, "    for (int l = 0; l < NUM_LAYERS; l++) {\n");
    fprintf(out, "        for (int idx = 0; idx < LAYER_DIM * LAYER_DIM; idx++) {\n");
    fprintf(out, "            sim.layers[l].weights.data[idx] = best_weights[l].data[idx];\n");
    fprintf(out, "        }\n");
    fprintf(out, "        matrix_free(&best_weights[l]);\n");
    fprintf(out, "    }\n\n");
    
    fprintf(out, "    sim_free(&sim);\n");
    fprintf(out, "    free(dataset_x); free(dataset_y);\n");
    fprintf(out, "    printf(\"=== Training complete! ===\\n\");\n");
    fprintf(out, "    return 0;\n");
    fprintf(out, "}\n");
    
    fclose(out);
    return 0;
}
